### ISSUE TITLE
Emptied Bin folder 

### ISSUE THREAD

**Issue by arhvel** [shangjingbo1226/DPPred#1]
Hi there!
I found your work fantastic.

I tried running the DPPred code on my dataset but I always run into the error below:
./bin/produce_candidate_patterns :not found
../bin/select_patterns: not found
./bin/rebuild_features: not found
./bin/ rebuild_features: not found
../bin/predict: not found

I will appreciate your feedback

Sincerely,
Victor.

**Comment by shangjingbo1226** [comment]
Please look at the Makefile and make sure that CXX is set to the correct version.
